config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "posts#index"
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :groups, only: [:index, :new, :create, :edit, :updata] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true
  validates :age, presence: true
  validates :height, presence: true
  validates :weight, presence: true


  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true 
  has_many :group_users
  has_many :groups, through: :group_users      
  has_many :posts
  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :tel, :email, :encrypted_password, :address, :Facility])
  end

  # def after_sign_out_path_for(resource)
  #   '/users/sign_in' # サインアウト後のリダイレクト先URL
  # end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
    else
      render :edit
    end
  end


  private
  def group_params
    params.require(:group).permit(:name, :age, :height, :weight, user_ids: [])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  def edit
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :名前, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: '利用者様の名前を入力してください'
    .chat-group-form__field--left
      = f.label :年齢, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :age, class: 'chat__group_name chat-group-form__input', placeholder: '利用者様の年齢を入力してください'
    .chat-group-form__field--left
      = f.label :身長, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :height, class: 'chat__group_name chat-group-form__input', placeholder: '利用者様の身長を入力してください'
    .chat-group-form__field--left
      = f.label :体重, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :weight, class: 'chat__group_name chat-group-form__input', placeholder: '利用者様の体重を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} メンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'posts/index'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kai
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    

app/views/posts/_message.html.haml
.message{data: {message: {id: message.id}}}
  .message-box
    .message-box__name 
      = message.user.name
    .message-box__date 
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .message-box__lower-message
    - if message.content.present?
      .message--box__lower-message
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/posts/index.html.haml
.wrapper 
  .header
    - if user_signed_in?  
      .header__left
        = current_user.name
      .header__center
        タイトル
      %ul.header__right
        %li.header__right--nenu
          = link_to new_group_path(current_user) do
            グループ設定
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'header__right--nenu'
        %li.header__right--nenu
          = link_to edit_user_path(current_user) do
            編集
    - else
      .header__left
        名前
      .header__center
        タイトル
      %ul.header__right
        %li.header__right--nenu
          = link_to 'users/sign_up' do
            新規登録
        %li.header__right--nenu
          = link_to new_user_session_path do
            ログイン
  .main
    .main--side__left
      .main--side__left__Photo
        写真
      .main--side__left__content
        .main--side__left__content__calendar
          <input type="date"></input>
        .main--side__left__content__calendar--text
          日付
        .main--side__left__content__calendar--text
          日付
        .main--side__left__content__calendar--text
          日付
    .main--center
      .main--center__data
        ◯月◯日の様子
      .main--center__box
        .main--center__box--message
          メッセージ
    .main--side__right
      .main--side__right__box
        .main--side__right__box__content
          .main--side__right__box__content__item
            名前  
          .main--side__right__box__content__item
            電話番号
          .main--side__right__box__content__item
            施設名
        .main--side__right__box__content
          .main--side__right__box__content__item
            名前  
          .main--side__right__box__content__item
            電話番号
          .main--side__right__box__content__item
            施設名
        .main--side__right__box__content
          .main--side__right__box__content__item
            名前  
          .main--side__right__box__content__item
            電話番号
          .main--side__right__box__content__item
            施設名
        .main--side__right__box__content
          .main--side__right__box__content__item
            名前  
          .main--side__right__box__content__item
            電話番号
          .main--side__right__box__content__item
            施設名
        .main--side__right__box__content
          .main--side__right__box__content__item
            名前  
          .main--side__right__box__content__item
            電話番号
          .main--side__right__box__content__item
            施設名
    
      .main--side__right__information
        %ul
          %li.main--side__right__information__name
            名前
          %li.main--side__right__information__tel
            電話番号
          %li.main--side__right__information__address
            住所
          %li.main--side__right__information__pressure
            血圧
            %li.main--side__right__information__pressure__hi
              最高血圧
            %li.main--side__right__information__pressure__low
              最低血圧


  .form
    = form_for [@group, @message] do |f|
      = f.text_field :content, class: 'form__message', placeholder: 'type a message'
      .form__mask
        = f.label :image, class: 'form__mask__image' do
          = 画像を投稿
          = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'form__submit'
      

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :名前
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :電話番号
          .field-input
            = f.text_field :tel  
        .field
          .field-label
            = f.label :メールアドレス
          .field-input
            = f.email_field :email
        .field
          .field-label
            = f.label :施設名
            %i (ご家族の方は入力しないでください)
          .field-input
            = f.text_field :Facility   
        .field
          .field-label
            = f.label :住所
          .field-input
            = f.text_field :address
        .field
        .actions
          = f.submit "保存", class: 'btn'